
#ifndef BOOST_CONTRACT_EXT_PP_BASE_TRAITS_AUX_INDEX_HPP_
#define BOOST_CONTRACT_EXT_PP_BASE_TRAITS_AUX_INDEX_HPP_

// WARNING: These index values must match parsing oder (see base.hpp).

#define BOOST_CONTRACT_EXT_PP_BASE_TRAITS_AUX_ACCESS_INDEX  0
#define BOOST_CONTRACT_EXT_PP_BASE_TRAITS_AUX_VIRTUAL_INDEX 1
#define BOOST_CONTRACT_EXT_PP_BASE_TRAITS_AUX_TYPE_INDEX    2

#endif // #include guard

