
#ifndef BOOST_CONTRACT_EXT_PP_CLASS_TRAITS_AUX_INDEX_HPP_
#define BOOST_CONTRACT_EXT_PP_CLASS_TRAITS_AUX_INDEX_HPP_

// WARNING: These index values must match parsing order (see class.hpp).

#define BOOST_CONTRACT_EXT_PP_CLASS_TRAITS_AUX_EXPORT_INDEX             0
#define BOOST_CONTRACT_EXT_PP_CLASS_TRAITS_AUX_TEMPLATE_INDEX           1
#define BOOST_CONTRACT_EXT_PP_CLASS_TRAITS_AUX_TEMPLATE_PARAMS_INDEX    2

#define BOOST_CONTRACT_EXT_PP_CLASS_TRAITS_AUX_FRIEND_INDEX             3

#define BOOST_CONTRACT_EXT_PP_CLASS_TRAITS_AUX_KEY_INDEX                4

#define BOOST_CONTRACT_EXT_PP_CLASS_TRAITS_AUX_VERBATIM_INDEX           5

#define BOOST_CONTRACT_EXT_PP_CLASS_TRAITS_AUX_NAME_INDEX               6

#define BOOST_CONTRACT_EXT_PP_CLASS_TRAITS_AUX_SPECIALIZATION_INDEX     7

#define BOOST_CONTRACT_EXT_PP_CLASS_TRAITS_AUX_FINAL_INDEX              8
#define BOOST_CONTRACT_EXT_PP_CLASS_TRAITS_AUX_VIRT_INDEX \
    BOOST_CONTRACT_EXT_PP_CLASS_TRAITS_AUX_FINAL_INDEX

#define BOOST_CONTRACT_EXT_PP_CLASS_TRAITS_AUX_BASES_INDEX              9

// Must be greater than all indexes (i.e., very last one).
#define BOOST_CONTRACT_EXT_PP_CLASS_TRAITS_AUX_MAX_INDEX                10

#endif // #include guard

