
#ifndef BOOST_CONTRACT_EXT_PP_TRAITS_AUX_TPARAM_INDEX_HPP_
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_TPARAM_INDEX_HPP_

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_TPARAM_INDEX_KIND      0
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_TPARAM_INDEX_NAME      1
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_TPARAM_INDEX_DEFAULT   2

#endif // #include guard

