
#ifndef BOOST_CONTRACT_EXT_PP_ALIAS_TRAITS_AUX_INDEX_HPP_
#define BOOST_CONTRACT_EXT_PP_ALIAS_TRAITS_AUX_INDEX_HPP_

#define BOOST_CONTRACT_EXT_PP_ALIAS_TRAITS_AUX_KIND_INDEX               0
#define BOOST_CONTRACT_EXT_PP_ALIAS_TRAITS_AUX_TEMPLATE_PARAMS_INDEX    1
#define BOOST_CONTRACT_EXT_PP_ALIAS_TRAITS_AUX_NAMESPACE_INDEX          2
#define BOOST_CONTRACT_EXT_PP_ALIAS_TRAITS_AUX_NEW_NAME_INDEX           3
#define BOOST_CONTRACT_EXT_PP_ALIAS_TRAITS_AUX_NAME_INDEX               4

#endif // #include guard

