
#ifndef BOOST_CONTRACT_EXT_PP_PARAM_TRAITS_AUX_INDEX_HPP_
#define BOOST_CONTRACT_EXT_PP_PARAM_TRAITS_AUX_INDEX_HPP_

#define BOOST_CONTRACT_EXT_PP_PARAM_TRAITS_AUX_TYPE_INDEX       0
#define BOOST_CONTRACT_EXT_PP_PARAM_TRAITS_AUX_NAME_INDEX       1
#define BOOST_CONTRACT_EXT_PP_PARAM_TRAITS_AUX_DEFAULT_INDEX    2

#endif // #include guard

