
#ifndef BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_ASSERTION_HPP_
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_ASSERTION_HPP_

// WARNING: These index values must match parsing order (see assertion.hpp).

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_ASSERTION_KEY                0

// All indexes below start from 1 (0 taken by "key", common to all assertions).

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_BOOL_ASSERTION_EXPR          1

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_CONST_ASSERTION_CAPTURES     1
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_CONST_ASSERTION_EXPR         2

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_IF_ASSERTION_COND            1
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_IF_ASSERTION_THENS           2
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_IF_ASSERTION_ELSES           3

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_RETURN_ASSERTION_TYPE        1
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_RETURN_ASSERTION_ASSIGN      2

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_OLDOF_ASSERTION_EXPR         1
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_OLDOF_ASSERTION_TYPE         2
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_OLDOF_ASSERTION_ASSIGN       3

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_NAMESPACE_ASSERTION_NEW_NAME 1
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_NAMESPACE_ASSERTION_NAME     2

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_USING_ASSERTION_TEMPLATE_PARAMS 1
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_USING_ASSERTION_NAMESPACE    2
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_USING_ASSERTION_NEW_NAME     3
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_USING_ASSERTION_NAME         4

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_TYPEDEF_ASSERTION_NAME       1
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_TYPEDEF_ASSERTION_NEW_NAME   2

#endif // #include guard

