
#ifndef BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_BASE_HPP_
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_BASE_HPP_

// WARNING: These index values must match parsing oder (see base.hpp).

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_BASE_ACCESS  0
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_BASE_VIRTUAL 1
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_BASE_TYPE    2

#endif // #include guard

