
#ifndef BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_CLASS_HPP_
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_CLASS_HPP_

// WARNING: These index values must match parsing order (see class.hpp).

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_CLASS_EXPORT             0
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_CLASS_TEMPLATE           1
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_CLASS_TEMPLATE_PARAMS    2

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_CLASS_FRIEND             3

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_CLASS_KEY                4

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_CLASS_VERBATIM           5

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_CLASS_NAME               6

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_CLASS_SPECIALIZATION     7

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_CLASS_FINAL              8
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_CLASS_VIRT \
    BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_CLASS_FINAL

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_CLASS_BASES              9

// Must be greater than all indexes (i.e., very last one).
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_CLASS_MAX                10

#endif // #include guard

