
#ifndef BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_HPP_
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_HPP_

// WARNING: These index values must match parsing order (see func.hpp).

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_ACCESS          0

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_VERBATIM        1

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_EXPORT          2
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_TEMPLATE        3
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_TEMPLATE_PARAMS 4

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_INLINE          5
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_STATIC          6
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_EXTERN          7
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_EXPLICIT        8
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_VIRTUAL         9
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_FRIEND          10
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_CLASSIFIERS \
    BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_FRIEND

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_RETURN          11

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_OPERATOR_NAME   12
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_NAME            13

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_PARAMS          14

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_CONST           15
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_VOLATILE        16
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_CV \
    BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_VOLATILE

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_REF             17

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_EXCEPT          18

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_TRAILING_RETURN 19

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_FINAL           20
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_OVERRIDE        21
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_VIRT \
    BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_OVERRIDE

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_PRECONDITIONS   22

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_POSTCONDITIONS  23

// Must be greater than all indexes (i.e., very last one).
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_FUNC_MAX             24

#endif // #include guard

