
#ifndef BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_PARAM_HPP_
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_PARAM_HPP_

// WARNING: Theses index values must match parsing oder (see param.hpp).

#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_PARAM_TYPE       0
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_PARAM_NAME       1
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_INDEX_PARAM_DEFAULT    2

#endif // #include guard

