
#ifndef BOOST_CONTRACT_CLASS_INVARIANT_HPP_
#define BOOST_CONTRACT_CLASS_INVARIANT_HPP_

/* PUBLIC */

#define BOOST_CONTRACT_CLASS_INVARIANT_TPL(...) \
    BOOST_CONTRACT_CLASS_INVARIANT_(0, __VA_ARGS__)

/* PRIVATE */

#define BOOST_CONTRACT_CLASS_INVARIANT_(is_template, ...) \
    };

#endif // #include guard

