
// Copyright (C) 2008-2012 Lorenzo Caminiti
// Distributed under the Boost Software License, Version 1.0
// (see accompanying file LICENSE_1_0.txt or a copy at
// http://www.boost.org/LICENSE_1_0.txt)
// Home at http://sourceforge.net/projects/contractpp

#ifndef CONTRACT_DETAIL_PP_IS_DIGIT_HPP_
#define CONTRACT_DETAIL_PP_IS_DIGIT_HPP_

// WARNING: FILE AUTOMATICALLY GENERATED, DO NOT MODIFY IT!
// Instead modify the generation script "<FILE>-generate.py" and run
// `$ python <FILE_NAME>-generate.py > FILE_NAME.hpp`.
// Used: #define BOOST_PP_LIMIT_MAG 256

#include <contract/detail/preprocessor/keyword/facilities/is.hpp>

// PUBLIC //

#define CONTRACT_DETAIL_PP_IS_DIGIT(tokens) \
    CONTRACT_DETAIL_PP_KEYWORD_FACILITY_IS_FRONT(tokens, \
            CONTRACT_DETAIL_PP_IS_DIGIT_)

// DATA //

#define CONTRACT_DETAIL_PP_IS_DIGIT_0 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_1 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_2 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_3 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_4 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_5 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_6 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_7 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_8 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_9 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_10 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_11 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_12 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_13 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_14 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_15 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_16 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_17 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_18 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_19 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_20 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_21 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_22 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_23 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_24 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_25 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_26 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_27 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_28 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_29 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_30 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_31 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_32 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_33 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_34 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_35 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_36 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_37 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_38 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_39 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_40 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_41 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_42 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_43 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_44 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_45 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_46 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_47 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_48 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_49 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_50 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_51 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_52 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_53 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_54 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_55 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_56 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_57 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_58 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_59 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_60 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_61 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_62 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_63 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_64 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_65 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_66 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_67 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_68 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_69 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_70 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_71 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_72 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_73 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_74 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_75 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_76 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_77 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_78 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_79 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_80 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_81 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_82 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_83 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_84 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_85 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_86 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_87 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_88 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_89 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_90 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_91 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_92 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_93 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_94 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_95 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_96 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_97 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_98 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_99 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_100 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_101 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_102 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_103 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_104 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_105 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_106 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_107 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_108 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_109 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_110 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_111 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_112 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_113 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_114 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_115 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_116 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_117 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_118 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_119 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_120 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_121 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_122 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_123 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_124 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_125 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_126 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_127 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_128 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_129 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_130 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_131 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_132 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_133 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_134 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_135 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_136 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_137 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_138 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_139 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_140 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_141 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_142 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_143 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_144 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_145 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_146 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_147 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_148 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_149 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_150 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_151 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_152 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_153 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_154 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_155 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_156 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_157 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_158 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_159 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_160 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_161 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_162 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_163 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_164 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_165 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_166 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_167 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_168 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_169 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_170 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_171 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_172 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_173 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_174 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_175 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_176 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_177 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_178 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_179 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_180 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_181 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_182 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_183 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_184 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_185 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_186 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_187 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_188 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_189 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_190 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_191 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_192 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_193 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_194 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_195 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_196 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_197 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_198 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_199 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_200 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_201 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_202 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_203 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_204 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_205 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_206 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_207 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_208 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_209 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_210 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_211 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_212 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_213 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_214 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_215 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_216 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_217 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_218 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_219 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_220 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_221 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_222 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_223 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_224 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_225 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_226 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_227 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_228 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_229 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_230 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_231 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_232 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_233 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_234 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_235 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_236 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_237 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_238 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_239 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_240 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_241 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_242 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_243 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_244 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_245 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_246 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_247 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_248 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_249 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_250 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_251 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_252 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_253 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_254 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_255 (1) /* unary */ 
#define CONTRACT_DETAIL_PP_IS_DIGIT_256 (1) /* unary */ 

#endif // #include guard

