
#ifndef BOOST_CONTRACT_EXT_PP_TRAITS_AUX_FUNC_INDEX_HPP_
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_FUNC_INDEX_HPP_

// WARNING: These indexes must match order traits are parsed (see func.hpp).
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_FUNC_INDEX_ACCESS      0
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_FUNC_INDEX_VERBATIM    1
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_FUNC_INDEX_EXPORT      2
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_FUNC_INDEX_TEMPLATE    3
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_FUNC_INDEX_TPARAMS     4
#define BOOST_CONTRACT_EXT_PP_TRAITS_AUX_FUNC_INDEX_DONE        5

#endif // #include guard

