
#ifndef BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_INDEX_HPP_
#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_INDEX_HPP_

// TODO: It is confusing to have all these many aux_ subdirs... move all those
// into a single traits/aux_/ as traits/aux_/func_index.hpp, etc.

// WARNING: These indexes must match order traits are parsed (see func.hpp).

#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_ACCESS_INDEX          0

#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_VERBATIM_INDEX        1

#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_EXPORT_INDEX          2
#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_TEMPLATE_INDEX        3
#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_TEMPLATE_PARAMS_INDEX 4

#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_INLINE_INDEX          5
#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_STATIC_INDEX          6
#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_EXTERN_INDEX          7
#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_EXPLICIT_INDEX        8
#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_VIRTUAL_INDEX         9
#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_FRIEND_INDEX          10
#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_CLASSIFIERS_INDEX \
    BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_FRIEND_INDEX

#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_RETURN_INDEX          11

#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_OPERATOR_NAME_INDEX   12
#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_NAME_INDEX            13

#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_PARAMS_INDEX          14

#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_CONST_INDEX           15
#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_VOLATILE_INDEX        16
#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_CV_INDEX \
    BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_VOLATILE_INDEX

#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_REF_INDEX             17

#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_EXCEPT_INDEX          18

#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_TRAILING_RETURN_INDEX 19

#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_FINAL_INDEX           20
#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_OVERRIDE_INDEX        21
#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_VIRT_INDEX \
    BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_OVERRIDE_INDEX

#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_POSTCONDITIONS_INDEX  22

// Must be greater than all indexes (i.e., very last one).
#define BOOST_CONTRACT_EXT_PP_FUNC_TRAITS_AUX_MAX_INDEX             23

#endif // #include guard

